apiVersion: v1
kind: ConfigMap
metadata:
  name: cli-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cli
data:
  admin_cli.toml: |
    log = 'WARN; default=stream:stream=stderr'
    [client.io_worker.ibsocket]
    max_sge = 1
    [storage_client.net_client.io_worker.ibsocket]
    max_sge = 1
    [storage_client.net_client_for_updates.io_worker.ibsocket]
    max_sge = 1
    [mgmtd_client]
    mgmtd_server_addresses = ["RDMA://mgmtd-{{ .Release.Name }}:8000"]
---
apiVersion: v1
kind: Pod
metadata:
  name: admin-cli-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: cli
spec:
  terminationGracePeriodSeconds: 2
  containers:
  - name: admin-cli
    image: registry-vpc.cn-beijing.aliyuncs.com/huweiwen-test/3fs-admin-cli:dev
    imagePullPolicy: Always
    args:
    - --cfg=/etc/3fs/admin_cli.toml
    - --config.cluster_id={{.Values.clusterID}}
    - --config.user_info.token=$(TOKEN)
    tty: true
    stdin: true
    stdinOnce: true
    securityContext:
      privileged: true
    volumeMounts:
    - name: config
      mountPath: /etc/3fs
    - name: fdb-cluster-file
      mountPath: /etc/foundationdb
    env:
    - name: TOKEN
      valueFrom:
        secretKeyRef:
          optional: true
          name: root-token
          key: token
    resources:
      limits:
        aliyun/erdma: "1"
        memory: "512Mi"
        cpu: "500m"
  volumes:
  - name: config
    configMap:
      name: cli-{{ .Release.Name }}
  - name: fdb-cluster-file
    configMap:
      name: fdb-meta-{{ .Release.Name }}-config
      items:
      - key: cluster-file
        path: fdb.cluster
