---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: fdb-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: fdb
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: fdb-{{ .Release.Name }}
rules:
  - apiGroups: [""]
    resources: [pods]
    verbs: [get, watch, update, patch, list]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: fdb-{{ .Release.Name }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: fdb-{{ .Release.Name }}
subjects:
  - kind: ServiceAccount
    name: fdb-{{ .Release.Name }}
---
apiVersion: apps.foundationdb.org/v1beta2
kind: FoundationDBCluster
metadata:
  name: fdb-meta-{{ .Release.Name }}
  labels:
    app.kubernetes.io/name: {{ .Chart.Name }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/component: fdb
spec:
  processCounts:
    cluster_controller: 1
    stateless: -1
  processes:
    general:
      podTemplate:
        spec:
          securityContext:
            fsGroup: 4059
            fsGroupChangePolicy: OnRootMismatch
          serviceAccountName: fdb-{{ .Release.Name }}
          containers:
          - name: foundationdb
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
          - name: foundationdb-kubernetes-sidecar
            resources:
              requests:
                cpu: 100m
                memory: 128Mi
      volumeClaimTemplate:
        spec:
          storageClassName: alibabacloud-disk-entry
          resources:
            requests:
              storage: 16Gi
  version: 7.1.61